<?php 
include('partials/header.php');
include('sections/inicio.php');
include('sections/sobre-mim.php');
include('sections/counter.php');
include('sections/experiencias-profissionais.php');
include('sections/skills.php');
include('partials/footer.php');
?>